-file("/usr/local/Cellar/erlang/20.2.2/lib/erlang/lib/parsetools-2.1.6/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(compiler_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/compiler_lexer.xrl", 48).

-file("/usr/local/Cellar/erlang/20.2.2/lib/erlang/lib/parsetools-2.1.6/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/compiler_lexer.erl", 307).
yystate() -> 90.

yystate(93, [83|Ics], Line, Tlen, _, _) ->
    yystate(91, Ics, Line, Tlen+1, 36, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 82 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 84, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(93, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,93};
yystate(92, [32|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 0, Tlen);
yystate(92, [9|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 0, Tlen);
yystate(92, [10|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line+1, Tlen+1, 0, Tlen);
yystate(92, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,92};
yystate(91, [69|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 36, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(91, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,91};
yystate(90, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [87|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [86|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [71|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [72|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [70|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [68|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [67|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [66|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(88, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line+1, Tlen+1, Action, Alen);
yystate(90, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [C|Ics], Line, Tlen, Action, Alen) when C >= 74, C =< 81 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [C|Ics], Line, Tlen, Action, Alen) when C >= 88, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(90, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(86, Ics, Line, Tlen+1, Action, Alen);
yystate(90, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,90};
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 18, Tlen);
yystate(89, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,89};
yystate(88, [62|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 0, Tlen);
yystate(88, [61|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 0, Tlen);
yystate(88, [60|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(88, [59|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 0, Tlen);
yystate(88, [58|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 0, Tlen);
yystate(88, [47|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 0, Tlen);
yystate(88, [45|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 0, Tlen);
yystate(88, [43|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 0, Tlen);
yystate(88, [42|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 0, Tlen);
yystate(88, [37|Ics], Line, Tlen, _, _) ->
    yystate(80, Ics, Line, Tlen+1, 0, Tlen);
yystate(88, [32|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 0, Tlen);
yystate(88, [9|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 0, Tlen);
yystate(88, [10|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line+1, Tlen+1, 0, Tlen);
yystate(88, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,88};
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 9, Tlen);
yystate(87, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,87};
yystate(86, [95|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 19, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(86, Ics, Line, Tlen+1, 19, Tlen);
yystate(86, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,86};
yystate(85, [82|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line, Tlen+1, 36, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(85, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,85};
yystate(84, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(83, [79|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 36, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(83, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,83};
yystate(82, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(81, [79|Ics], Line, Tlen, _, _) ->
    yystate(85, Ics, Line, Tlen+1, 36, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,81};
yystate(80, [32|Ics], Line, Tlen, _, _) ->
    yystate(84, Ics, Line, Tlen+1, 29, Tlen);
yystate(80, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,80};
yystate(79, [87|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 12, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 86 ->
    yystate(39, Ics, Line, Tlen+1, 12, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 88, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 12, Tlen);
yystate(79, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,79};
yystate(78, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 10, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,77};
yystate(76, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line+1, Tlen+1, Action, Alen);
yystate(76, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 40 ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [C|Ics], Line, Tlen, Action, Alen) when C >= 42 ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(76, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,76};
yystate(75, [78|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 36, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,75};
yystate(74, [82|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 36, Tlen);
yystate(74, [72|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 36, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 71 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 73, C =< 81 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,74};
yystate(73, [70|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 36, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 69 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 71, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(73, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,73};
yystate(72, [32|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 1, Tlen);
yystate(72, [9|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 1, Tlen);
yystate(72, [10|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line+1, Tlen+1, 1, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,72};
yystate(71, [84|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 36, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(71, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,71};
yystate(70, [73|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 36, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 72 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,70};
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 13, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,69};
yystate(68, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(67, [79|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 36, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(67, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,67};
yystate(66, [84|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 36, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,66};
yystate(65, [69|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 36, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,65};
yystate(64, [32|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,64};
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 15, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,63};
yystate(62, [69|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 36, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,62};
yystate(61, [76|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 36, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 75 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 77, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,61};
yystate(60, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(59, [69|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 36, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,59};
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 6, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,58};
yystate(57, [73|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 36, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 72 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,57};
yystate(56, [32|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 25, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line,56};
yystate(55, [71|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 36, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 72, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,55};
yystate(54, [73|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 36, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 72 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,54};
yystate(53, [72|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 36, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 71 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 73, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,53};
yystate(52, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line};
yystate(51, [73|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 36, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 72 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,51};
yystate(50, [76|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 36, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 75 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 77, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,50};
yystate(49, [87|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [73|Ics], Line, Tlen, _, _) ->
    yystate(73, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [71|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [72|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [70|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 69 ->
    yystate(39, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 86 ->
    yystate(39, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 88, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,49};
yystate(48, [32|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 26, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,48};
yystate(47, [78|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 36, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,47};
yystate(46, [69|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 36, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,46};
yystate(45, [68|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 36, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 67 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 69, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,45};
yystate(44, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 3, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,43};
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 11, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,42};
yystate(41, [78|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 36, Tlen);
yystate(41, [77|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(41, [76|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 36, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 75 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,41};
yystate(40, [32|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 28, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line,40};
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,39};
yystate(38, [65|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 36, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,38};
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 16, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,37};
yystate(36, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(35, [61|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 33, Tlen);
yystate(35, [32|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 33, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,35};
yystate(34, [82|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 36, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,34};
yystate(33, [82|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 36, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,33};
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(32, Ics, Line, Tlen+1, 20, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,32};
yystate(31, [32|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 35, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,31};
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 2, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,30};
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 17, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,29};
yystate(28, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(27, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line};
yystate(26, [79|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 36, Tlen);
yystate(26, [72|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 36, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 71 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 73, C =< 78 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,26};
yystate(25, [77|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 36, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 76 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 78, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,25};
yystate(24, [32|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 24, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,24};
yystate(23, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line};
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 14, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,22};
yystate(21, [79|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 36, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,21};
yystate(20, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(20, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,20};
yystate(19, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 30, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line,19};
yystate(18, [69|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 36, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,18};
yystate(17, [82|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 36, Tlen);
yystate(17, [80|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(17, [81|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(17, [79|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 36, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,17};
yystate(16, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(15, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line};
yystate(14, [78|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 36, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,14};
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,13};
yystate(12, [32|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 23, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line,12};
yystate(11, [62|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 32, Tlen);
yystate(11, [61|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 32, Tlen);
yystate(11, [32|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 32, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line,11};
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 8, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,10};
yystate(9, [70|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 36, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 69 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 71, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,9};
yystate(8, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line};
yystate(7, [32|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 31, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line,7};
yystate(6, [69|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 36, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,6};
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 5, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,5};
yystate(4, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line};
yystate(3, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(2, [65|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 36, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,2};
yystate(1, [68|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 36, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 67 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 69, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 36, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,1};
yystate(0, [32|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 34, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, _) ->
    yyaction_0();
yyaction(1, _, _, _) ->
    yyaction_1();
yyaction(2, _, _, TokenLine) ->
    yyaction_2(TokenLine);
yyaction(3, _, _, TokenLine) ->
    yyaction_3(TokenLine);
yyaction(4, _, _, TokenLine) ->
    yyaction_4(TokenLine);
yyaction(5, _, _, TokenLine) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, _, _, TokenLine) ->
    yyaction_18(TokenLine);
yyaction(19, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars, TokenLine);
yyaction(20, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars, TokenLine);
yyaction(21, _, _, TokenLine) ->
    yyaction_21(TokenLine);
yyaction(22, _, _, TokenLine) ->
    yyaction_22(TokenLine);
yyaction(23, _, _, TokenLine) ->
    yyaction_23(TokenLine);
yyaction(24, _, _, TokenLine) ->
    yyaction_24(TokenLine);
yyaction(25, _, _, TokenLine) ->
    yyaction_25(TokenLine);
yyaction(26, _, _, TokenLine) ->
    yyaction_26(TokenLine);
yyaction(27, _, _, TokenLine) ->
    yyaction_27(TokenLine);
yyaction(28, _, _, TokenLine) ->
    yyaction_28(TokenLine);
yyaction(29, _, _, TokenLine) ->
    yyaction_29(TokenLine);
yyaction(30, _, _, TokenLine) ->
    yyaction_30(TokenLine);
yyaction(31, _, _, TokenLine) ->
    yyaction_31(TokenLine);
yyaction(32, _, _, TokenLine) ->
    yyaction_32(TokenLine);
yyaction(33, _, _, TokenLine) ->
    yyaction_33(TokenLine);
yyaction(34, _, _, TokenLine) ->
    yyaction_34(TokenLine);
yyaction(35, _, _, TokenLine) ->
    yyaction_35(TokenLine);
yyaction(36, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_36(TokenChars);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/0}).
-file("src/compiler_lexer.xrl", 8).
yyaction_0() ->
     skip_token .

-compile({inline,yyaction_1/0}).
-file("src/compiler_lexer.xrl", 9).
yyaction_1() ->
     skip_token .

-compile({inline,yyaction_2/1}).
-file("src/compiler_lexer.xrl", 10).
yyaction_2(TokenLine) ->
     { token, { 'VAR', TokenLine } } .

-compile({inline,yyaction_3/1}).
-file("src/compiler_lexer.xrl", 11).
yyaction_3(TokenLine) ->
     { token, { 'BEGIN', TokenLine } } .

-compile({inline,yyaction_4/1}).
-file("src/compiler_lexer.xrl", 12).
yyaction_4(TokenLine) ->
     { token, { 'END', TokenLine } } .

-compile({inline,yyaction_5/1}).
-file("src/compiler_lexer.xrl", 13).
yyaction_5(TokenLine) ->
     { token, { 'READ', TokenLine } } .

-compile({inline,yyaction_6/1}).
-file("src/compiler_lexer.xrl", 14).
yyaction_6(TokenLine) ->
     { token, { 'WRITE', TokenLine } } .

-compile({inline,yyaction_7/1}).
-file("src/compiler_lexer.xrl", 15).
yyaction_7(TokenLine) ->
     { token, { 'IF', TokenLine } } .

-compile({inline,yyaction_8/1}).
-file("src/compiler_lexer.xrl", 16).
yyaction_8(TokenLine) ->
     { token, { 'THEN', TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("src/compiler_lexer.xrl", 17).
yyaction_9(TokenLine) ->
     { token, { 'ELSE', TokenLine } } .

-compile({inline,yyaction_10/1}).
-file("src/compiler_lexer.xrl", 18).
yyaction_10(TokenLine) ->
     { token, { 'ENDIF', TokenLine } } .

-compile({inline,yyaction_11/1}).
-file("src/compiler_lexer.xrl", 19).
yyaction_11(TokenLine) ->
     { token, { 'WHILE', TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("src/compiler_lexer.xrl", 20).
yyaction_12(TokenLine) ->
     { token, { 'DO', TokenLine } } .

-compile({inline,yyaction_13/1}).
-file("src/compiler_lexer.xrl", 21).
yyaction_13(TokenLine) ->
     { token, { 'ENDWHILE', TokenLine } } .

-compile({inline,yyaction_14/1}).
-file("src/compiler_lexer.xrl", 22).
yyaction_14(TokenLine) ->
     { token, { 'TO', TokenLine } } .

-compile({inline,yyaction_15/1}).
-file("src/compiler_lexer.xrl", 23).
yyaction_15(TokenLine) ->
     { token, { 'DOWNTO', TokenLine } } .

-compile({inline,yyaction_16/1}).
-file("src/compiler_lexer.xrl", 24).
yyaction_16(TokenLine) ->
     { token, { 'FOR', TokenLine } } .

-compile({inline,yyaction_17/1}).
-file("src/compiler_lexer.xrl", 25).
yyaction_17(TokenLine) ->
     { token, { 'FROM', TokenLine } } .

-compile({inline,yyaction_18/1}).
-file("src/compiler_lexer.xrl", 26).
yyaction_18(TokenLine) ->
     { token, { 'ENDFOR', TokenLine } } .

-compile({inline,yyaction_19/2}).
-file("src/compiler_lexer.xrl", 27).
yyaction_19(TokenChars, TokenLine) ->
     { token, { identifier, TokenLine, TokenChars } } .

-compile({inline,yyaction_20/2}).
-file("src/compiler_lexer.xrl", 28).
yyaction_20(TokenChars, TokenLine) ->
     { token, { number, TokenLine, TokenChars } } .

-compile({inline,yyaction_21/1}).
-file("src/compiler_lexer.xrl", 29).
yyaction_21(TokenLine) ->
     { token, { '[', TokenLine } } .

-compile({inline,yyaction_22/1}).
-file("src/compiler_lexer.xrl", 30).
yyaction_22(TokenLine) ->
     { token, { ']', TokenLine } } .

-compile({inline,yyaction_23/1}).
-file("src/compiler_lexer.xrl", 31).
yyaction_23(TokenLine) ->
     { token, { ';', TokenLine } } .

-compile({inline,yyaction_24/1}).
-file("src/compiler_lexer.xrl", 32).
yyaction_24(TokenLine) ->
     { token, { ':=', TokenLine } } .

-compile({inline,yyaction_25/1}).
-file("src/compiler_lexer.xrl", 33).
yyaction_25(TokenLine) ->
     { token, { '+', TokenLine } } .

-compile({inline,yyaction_26/1}).
-file("src/compiler_lexer.xrl", 34).
yyaction_26(TokenLine) ->
     { token, { '-', TokenLine } } .

-compile({inline,yyaction_27/1}).
-file("src/compiler_lexer.xrl", 35).
yyaction_27(TokenLine) ->
     { token, { '*', TokenLine } } .

-compile({inline,yyaction_28/1}).
-file("src/compiler_lexer.xrl", 36).
yyaction_28(TokenLine) ->
     { token, { '/', TokenLine } } .

-compile({inline,yyaction_29/1}).
-file("src/compiler_lexer.xrl", 37).
yyaction_29(TokenLine) ->
     { token, { '%', TokenLine } } .

-compile({inline,yyaction_30/1}).
-file("src/compiler_lexer.xrl", 38).
yyaction_30(TokenLine) ->
     { token, { '=', TokenLine } } .

-compile({inline,yyaction_31/1}).
-file("src/compiler_lexer.xrl", 39).
yyaction_31(TokenLine) ->
     { token, { '<>', TokenLine } } .

-compile({inline,yyaction_32/1}).
-file("src/compiler_lexer.xrl", 40).
yyaction_32(TokenLine) ->
     { token, { '<', TokenLine } } .

-compile({inline,yyaction_33/1}).
-file("src/compiler_lexer.xrl", 41).
yyaction_33(TokenLine) ->
     { token, { '>', TokenLine } } .

-compile({inline,yyaction_34/1}).
-file("src/compiler_lexer.xrl", 42).
yyaction_34(TokenLine) ->
     { token, { '<=', TokenLine } } .

-compile({inline,yyaction_35/1}).
-file("src/compiler_lexer.xrl", 43).
yyaction_35(TokenLine) ->
     { token, { '>=', TokenLine } } .

-compile({inline,yyaction_36/1}).
-file("src/compiler_lexer.xrl", 44).
yyaction_36(TokenChars) ->
     { error, TokenChars } .

-file("/usr/local/Cellar/erlang/20.2.2/lib/erlang/lib/parsetools-2.1.6/include/leexinc.hrl", 313).
